version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    networks:
      - laravel
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - laravel
    depends_on:
      - elasticsearch

  fluentd:
    build:
      context: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Mount Docker logs directory
      - laravel_logs:/var/log/laravel
    networks:
      - laravel
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - ENVIRONMENT=local
networks:
  laravel:
    external: true

volumes:
  laravel_logs: # Declare the named volume here
    name: laravel_logs
    external: true